name: SnowSQL
env:
  SNOWSQL_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SNOWSQL_USER: ${{ secrets.SF_USER }}
  SNOWSQL_PASSWORD: ${{ secrets.SF_PASSWORD }}
  SNOWSQL_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}
    
on: push                                                  
jobs:                         
  executequery:                           
    name: Install SnowSQL                          
    runs-on: ubuntu-latest                           
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Download SnowSQL
      run:  curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
    - name: Install SnowSQL
      run: SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
    - name: List the values
      run: cat ~/.profile
    - name: Warehouse-1
      run: echo "$SNOWSQL_WAREHOUSE"
    - name: Account-1
      run: echo "$SNOWSQL_ACCOUNT"
    - name: UserDetails-1
      run: echo "$SNOWSQL_USER"
    - name: Check
      run: |
       if [ -z "$SNOWSQL_PASSWORD" ]; then
            echo "Empty Password"
       else
            echo " Not Empty"
       fi
    - name: Test installation
      run:  ~/snowflake/snowsql -v