name: SnowSQL

   
on: push

jobs:
  env: 
    SNOWSQL_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
    SNOWSQL_USER: ${{ secrets.SF_USER }}
    SNOWSQL_PASSWORD: ${{ secrets.SF_PASSWORD }}

        executequery:                           
          name: Install SnowSQL                          
          runs-on: ubuntu-latest     
